package com.leadtone.riders;

public class DBConstants {
    
    public static final String mobileSQL = "SELECT P.PUSHUSER_ID, P.NODE_ID,UTL_RAW.CAST_TO_VARCHAR2(UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(NVL(P.LOGIN_PASS,0)))) LOGIN_PASS,TO_CHAR (P.REG_TIME, 'YYYYMMDDHH24MISS') REG_TIME, TO_CHAR (P.UNREG_TIME, 'YYYYMMDDHH24MISS') UNREG_TIME, TO_CHAR (P.ACTIVE_TIME, 'YYYYMMDDHH24MISS') ACTIVE_TIME, TO_CHAR (P.UPDATE_TIME, 'YYYYMMDDHH24MISS') UPDATE_TIME, P.USER_STATUS,P.BOSS_STATUS, P.BLACK_WHITE, 3 AS DAY_FILER, P.DEV_ID,P.CLIENT_VERSION,0 AS LOGIN_FLAG, P.MAX_SIZE, P.COLOR, P.CHARSET, A.EMAIL_ADDR FROM PUSH_USER P, POP3_USER A  WHERE P.PUSHUSER_ID =:mobile AND A.PUSHUSER_ID = P.PUSHUSER_ID";
    
    
   
    
}
