package com.leadtone.riders;

public class DBConstants {
    
    public static final String mobileSQL = "SELECT P.PUSHUSER_ID, P.NODE_ID,UTL_RAW.CAST_TO_VARCHAR2(UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(NVL(P.LOGIN_PASS,0)))) LOGIN_PASS,TO_CHAR (P.REG_TIME, 'YYYYMMDDHH24MISS') REG_TIME, TO_CHAR (P.UNREG_TIME, 'YYYYMMDDHH24MISS') UNREG_TIME, TO_CHAR (P.ACTIVE_TIME, 'YYYYMMDDHH24MISS') ACTIVE_TIME, TO_CHAR (P.UPDATE_TIME, 'YYYYMMDDHH24MISS') UPDATE_TIME, P.USER_STATUS,P.BOSS_STATUS, P.BLACK_WHITE, 3 AS DAY_FILER, P.DEV_ID,P.CLIENT_VERSION,0 AS LOGIN_FLAG, P.MAX_SIZE, P.COLOR, P.CHARSET, A.EMAIL_ADDR FROM PUSH_USER P, POP3_USER A  WHERE P.PUSHUSER_ID =:mobile AND A.PUSHUSER_ID = P.PUSHUSER_ID";
    
    public static final String emailSQL = "SELECT EMAIL_ADDR,PUSHUSER_ID,MS_ID,ACCOUNT_STATUS,POP3_ACCOUNT,POP3_PASS,SMTP_ACCOUNT,SMTP_PASS,SMTP_REPLY_TO,SMTP_FROM_ADDR,0 AS PASS_WRONG_COUNT,3 AS AUTH_DENY_COUNT ,0 AS INIT_COUNT  FROM POP3_USER WHERE EMAIL_ADDR=:email";
    
    public static final String serverSQL = "SELECT P.MS_ID,P.DOMAIN_ID,P.POP3_SERVER_ADDR,P.POP3_PORT,P.SERVER_PASS,P.SMTP_SERVER_ADDR,P.SMTP_PORT,P.SMTP_CHARSET,P.SMTP_AUTH,P.SYNC_AUTH_TYPE,P.POP3_SSL,P.SMTP_SSL,D.AUTHCODE FROM POP3_SERVER P,DOMAIN D  WHERE P.MS_ID=:server AND D.DOMAIN_ID=P.DOMAIN_ID";
    
    public static final String configSQL = "SELECT P.PROPERTY_VALUE,P.CODE_TYPE FROM SYS_SETTING_REPOSITORY P WHERE P.PROPERTY_NAME=:config";
    
    public static final String portalServerSQL = "SELECT MS_ID,POP3_SERVER_ADDR,POP3_PORT,SMTP_SERVER_ADDR,SMTP_PORT,SMTP_CHARSET,POP3_SSL,SMTP_SSL,HOST_IP,FETCH_TYPE,CONCURRENCY FROM POP3_PORTAL_SERVER WHERE MS_ID=:msId";
    
    public static final String portalUserSQL = "SELECT PUSHUSER_ID,EMAIL_ADDR,ACCOUNT_STATUS,POP3_ACCOUNT,POP3_PASS,SMTP_ACCOUNT,SMTP_PASS,SMTP_REPLY_TO,SMTP_FROM_ADDR,TO_CHAR (ACC_ST_CHG_TIME, 'YYYYMMDDHH24MISS') ACC_ST_CHG_TIME,POP3_SSL,SMTP_SSL FROM POP3_PORTAL_USER WHERE EMAIL_ADDR=:emailAddr";
    
    public static final String newClientSQL = "SELECT P.PUSHUSER_ID PI, A.PHONE_TYPE PT,A.CLIENT_VER CV , A.MODEL MO,A.RESOLUTION RE ,P.CHARSET CH,P.MAX_SIZE MS,'gzip' CT,A.DEVICE_TOKEN DT,A.PUSH_TYPE PU FROM PUSH_USER P LEFT JOIN POST_USER_ACCOUNT A ON P.PUSHUSER_ID=A.PUSHUSER_ID WHERE P.PUSHUSER_ID=:mobile";
    
   
    
}
